---
title: "completejourney"
author: "Team"
date: "2025-11-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Packages
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ggplot2)
  library(here)
  library(completejourney)
  
  # we have not seen much of these packages in class so I included a summary
  library(lubridate) #standardizes and converts dates into usable data
  library(janitor) #easier cleaner for duplicates, NA(s), and inconsistencies
})
```

# Taking a look at the "Complete Journey" dataset
```{r}
# Note: use the glimpse function with:
# "transactions_sample" to see spending/purchasing info
# "products" to see product info
# "demographics" to see household info

transactions <- get_transactions()
products <- products
demographics <- demographics
promotions <- get_promotions()

glimpse(transactions)
glimpse(products)
glimpse(demographics)
```

# Editing/Sorting data
```{r}
# checking for NA percentage
na_percent <- function(df) {
  sapply(df, function(x) mean(is.na(x)) * 100)
}

na_percent(transactions)
na_percent(products)
na_percent(demographics)
na_percent(promotions)

# removing NA values in package_category, package_type + removing package_size, home_ownership, marital_status -- cleaning

products_clean <- products %>% filter( # removes NA(s)
  !is.na(product_category),
  !is.na(product_type)
  ) %>% select( # keeps only listed columns
    product_id,
    manufacturer_id,
    department,
    brand,
    product_category,
    product_type
  )

demographics_clean <- demographics %>% select(
  household_id,
  age,
  income,
  household_size
)


# creating time features: year, month, week, day of week + seasons: winter, spring, summer, fall

transactions <- transactions %>% mutate(
  transaction_timestamp = ymd_hms(transaction_timestamp),
  year = year(transaction_timestamp),
  month = month(transaction_timestamp),
  week = week(transaction_timestamp),
  day_of_week = wday(transaction_timestamp, label = TRUE),

  seasons = case_when(
    month %in% c(12, 1, 2) ~ "Winter",
    month %in% c(3, 4, 5) ~ "Spring",
    month %in% c(6, 7, 8) ~ "Summer",
    month %in% c(9, 10, 11) ~ "Fall"
  )
) %>% select(-transaction_timestamp)

#group promotions into one singular per store ID per day instead of having multiple promotions per store ID per day.
promotions <- promotions %>% group_by(product_id, store_id, week) %>% summarize(
  any_display = any(!is.na(display_location)),
  any_mailer = any(!is.na(mailer_location)),
  .groups = "drop" # tells r to return an ungroup data frame after summarizing
)

# check NA values again
na_percent(products_clean)
na_percent(demographics_clean)
na_percent(promotions)

# now merge transactions with the products data and the demographics dataset

customer_data <- transactions %>%
  left_join(products_clean, by = "product_id") %>%
  left_join(demographics_clean, by = "household_id") %>%
  left_join(promotions, by = c("product_id", "store_id", "week"))

na_percent(customer_data)

# removing rows with missing demographic and product info -- cleaning
customer_data <- customer_data %>% filter(
  !is.na(age),
  !is.na(income),
  !is.na(household_size)
)

customer_data <- customer_data %>% filter(
  !is.na(product_category),
  !is.na(product_type),
  !is.na(manufacturer_id)
)

# promotions had a high number of NA = days when there were no promotions -- so we change NA (days with no promotion) to FALSE values
customer_data <- customer_data %>% mutate(
  any_display = if_else(is.na(any_display), FALSE, any_display),
  any_mailer = if_else(is.na(any_mailer), FALSE, any_mailer)
)

na_percent(customer_data)


#establishing a weight_department and removing them bc they complicate quatity and sales

weight_departments <- c("MEAT-PCKGD", "MEAT", "PRODUCE", "DELI", "SEAFOOD-PCKGD")

customer_data <- customer_data %>%
  filter(!(department %in% weight_departments))

#there are $0 sales with 0 purchase quantity, removing those
customer_data_clean <- customer_data %>%
    filter(sales_value > 0,
           quantity > 0)

#checking for outliers in new dataset
summary(customer_data_clean$quantity)
quantile(customer_data_clean$quantity, probs = c(0.99,0.995,0.999), na.rm = TRUE)

# creating age groups, income brackets, household size, total spend & quantity per basket, customer-level summarizations

#before proceeding, I want to check what entries/groups are being used in the original data
unique(customer_data$age)
unique(customer_data$income)
unique(customer_data$household_size)

#proceeding cleaning into new data frame = "customer_data_clean"
customer_data_clean <- customer_data_clean %>% mutate(
  age = case_when(
    age %in% c("19-24", "25-34") ~ "18-34",
    age %in% c("35-44", "45-54") ~ "35-54",
    age %in% c("55-64", "65+") ~ "55+",
    TRUE ~ "Unknown"
  )
) %>% mutate(
  income = case_when(
    income %in% c("Under 15K", "15-24K", "25-34K", "35-49K") ~ "Low Income",
    income %in% c("50-74K", "75-99K", "100-124K") ~ "Middle Income",
    income %in% c("125-149K", "150-174K", "175-199K", "200-249K", "250K+") ~ "High Income",
    TRUE ~ "Unknown"
  )
) %>% mutate(
  household_size = case_when(
    household_size %in% c("1", "2") ~ "1-2",
    household_size %in% c("3", "4") ~ "3-4",
    household_size %in% c("5+") ~ "5+",
    TRUE ~ "Unknown"
  )
)

#removing extreme outliers
customer_data_clean <- customer_data_clean %>%
    filter(quantity <= 40)

basket_level <- customer_data_clean %>% group_by(household_id, basket_id) %>% summarize(
  basket_total_spend = sum(sales_value, na.rm = TRUE),
  basket_total_quantity = sum(quantity, na.rm = TRUE),
  seasons = first(seasons),
  age = first(age),
  income = first(income),
  household_size = first(household_size),
  .groups = "drop"
)

customer_summary <- basket_level %>% group_by(household_id) %>% summarize(
  age = first(age),
  income = first(income),
  household_size = first(household_size),
    
  total_spend = sum(basket_total_spend),
  total_quantity = sum(basket_total_quantity),
  num_trips = n(),
  avg_quantity_per_trip = total_quantity / num_trips,
  avg_basket_value = total_spend / num_trips,
  fav_season = names(which.max(table(seasons)))
)



#readr::write_csv(customer_summary, "customer_summary.csv")
#readr::write_csv(customer_data_clean, "customer_data_clean.csv")


#Note to self: cmd + shift + m = %>% 
#NOTE: I am uploading the markdown to GitHub in increments so the one you have will have less than what I have.
```

#Visualizations by Income
```{r}
#vis 1 - bar chart : avg total spend by inc group
customer_summary %>%
  group_by(income) %>%
  summarize(avg_total_spend = mean(total_spend)) %>%
  ggplot(aes(x = income, y = avg_total_spend, fill = income)) +
  geom_col() +
  labs(
    title = "Average Total Spending by Income Group",
    x = "Income Group",
    y = "Average Total Spend ($)"
  ) +
  theme_minimal() +
  theme(legend.position = "none")
# higher inc households spend the most
# mid inc households spend less
# low inc households spend the least
# = income is positively related to total spending

#vis 2 - bar chart : avg num of trips by inc group
customer_summary %>%
  group_by(income) %>%
  summarize(avg_trips = mean(num_trips)) %>%
  ggplot(aes(x = income, y = avg_trips, fill = income)) +
  geom_col() +
  labs(
    title = "Average Number of Grocery Trips by Income Group",
    x = "Income Group",
    y = "Average Number of Trips"
  ) +
  theme_minimal() +
  theme(legend.position = "none")
# higher inc households take more total trips
# low inc households take fewer
# = more frequent shopping among higher-income customers
```

#Visualizations by Age
```{r}
#vis 1 - avg total spend by age group
customer_summary %>%
  group_by(age) %>%
  summarise(avg_spend = mean(total_spend)) %>%
  ggplot(aes(x = age, y = avg_spend, fill = age)) +
  geom_col() +
  labs(
    title = "Average Spending by Age Group",
    subtitle = "Older age groups tend to spend more overall",
    x = "Age Group",
    y = "Average Total Spend ($)"
  ) +
  theme_minimal()

#vis 2 - avg num of trips by age
customer_summary %>%
  group_by(age) %>%
  summarise(avg_trips = mean(num_trips)) %>%
  ggplot(aes(x = age, y = avg_trips, fill = age)) +
  geom_col() +
  labs(
    title = "Shopping Frequency Across Age Groups",
    subtitle = "Which ages shop most often?",
    x = "Age Group",
    y = "Average Number of Trips"
  ) +
  theme_minimal()

```

#Visualization by Household Size
```{r}
#vis 1 - total spend by household size
customer_summary %>%
  group_by(household_size) %>%
  summarise(avg_spend = mean(total_spend)) %>%
  ggplot(aes(x = household_size, y = avg_spend, fill = household_size)) +
  geom_col() +
  labs(
    title = "Average Spending by Household Size",
    subtitle = "Larger households tend to spend more overall",
    x = "Household Size",
    y = "Average Total Spend ($)"
  ) +
  theme_minimal()

#vis 2 - num of trips by household size
customer_summary %>%
  group_by(household_size) %>%
  summarise(avg_trips = mean(num_trips)) %>%
  ggplot(aes(x = household_size, y = avg_trips, fill = household_size)) +
  geom_col() +
  labs(
    title = "Shopping Frequency by Household Size",
    subtitle = "Do larger households shop more often?",
    x = "Household Size",
    y = "Average Number of Trips"
  ) +
  theme_minimal()
```

